name: mars
description: Mars in the meta universe.
publish_to: none
version: 1.0.4+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  # sdk: ">=2.7.0 <3.0.0"
  # sdk: ">=2.0.0-dev.68.0 <3.0.0"
  # flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Internationalization
  flutter_localizations:
    sdk: flutter

  ## intl: ^0.16.1
  intl: ^0.17.0
  ## easy_localization: ^2.3.3
  easy_localization: ^3.0.0

  # Config/Tools
  ## flutter_dotenv: ^2.1.0
  flutter_dotenv: ^5.0.2
  ## flutter_flipperkit:
  ##  path: ./third_party/flutter_flipperkit
  flutter_flipperkit: ^0.0.28
  ## logger: ^0.9.4
  logger: ^1.1.0
  ## sprintf: ^5.0.0
  sprintf: ^6.0.0
  ## uuid: ^2.2.2
  uuid: ^3.0.6
  ## random_string: ^2.1.0
  random_string: ^2.3.1
  ## mime_type: ^0.3.2
  mime_type: ^1.0.0
  ## path: ^1.7.0
  path: ^1.8.0
  ## path_provider: ^1.6.24
  path_provider: ^2.0.10
  ## device_info: ^1.0.0
  device_info: ^2.0.3
  ## package_info: ^0.4.3+2
  package_info: ^2.0.2
  ## decimal: ^0.3.5
  decimal: ^2.2.0
  ## permission_handler: ^5.0.1+1
  permission_handler: ^9.2.0
  ## supercharged: ^1.12.0
  supercharged: ^2.1.1

  # Crashes / Analytics
  ## sentry: ^4.0.1
  sentry: ^6.5.1
  ## sentry_flutter: ^4.0.1
  sentry_flutter: ^6.5.1
  ## amplitude_flutter: ^2.2.3
  amplitude_flutter: ^3.9.0

  # Network
  ## dio: ^3.0.10
  dio: ^4.0.6
  ## dio_http2_adapter: ^1.0.1
  dio_http2_adapter: ^2.0.0
  ## dio_flutter_transformer: ^3.0.2
  ## connectivity: ^2.0.2
  connectivity: ^3.0.6
  network_flutter:
    git: https://github.com/metabasenetwork/network_flutter2

  # UI
  ## oktoast: ^2.3.2
  oktoast: ^3.1.5
  ## pull_to_refresh: 1.6.3
  pull_to_refresh: ^2.0.0
  ## flutter_sticky_header: ^0.5.0
  flutter_sticky_header: ^0.6.2
  ## flutter_xlider: ^3.4.0
  flutter_xlider: ^3.4.0
  ## rive: ^0.6.5
  rive: ^0.8.4
  ## simple_animations: ^2.4.2
  simple_animations: ^4.0.2
  ## scroll_to_index: ^1.0.6
  scroll_to_index: ^2.1.1
  ## dotted_border: ^1.0.7
  dotted_border: ^2.0.0+2
  ## flutter_group_sliver: ^0.0.2
  flutter_group_sliver: ^0.0.2
  ## flutter_linkify: ^4.0.2
  flutter_linkify: ^5.0.2

  # Store, State and DB
  ## get_it: ^5.0.3
  get_it: ^7.2.0
  ## async_redux: ^6.0.3
  async_redux: ^15.0.0
  ## built_value: ^7.1.0
  built_value: ^8.3.0
  ## built_collection: ^4.3.2
  built_collection: ^5.1.1
  ## shared_preferences: ^0.5.12+4
  shared_preferences: ^2.0.15
  ## rxdart: ^0.24.1
  rxdart: ^0.27.3
  ## bloc: ^6.1.1
  bloc: ^8.0.3
  ## flutter_bloc: ^6.1.1
  flutter_bloc: ^8.0.1
  ## flutter_hooks: ^0.15.0
  flutter_hooks: ^0.18.2+1
  ## flutter_secure_storage: ^3.3.5
  flutter_secure_storage: ^5.0.2
  ## hive: ^1.4.4+1
  hive: ^2.2.1
  ## hive_flutter: ^0.3.1
  hive_flutter: ^1.1.0

  # Mqtt
  ## lzstring: ^1.0.2+1
  lzstring: ^2.0.0+2
  ## mqtt_client: ^8.1.0
  mqtt_client: ^9.6.8

  # Charts
  ## fl_chart: ^0.12.2
  fl_chart: ^0.50.6
  ## flutter_k_chart:
  ##   path: ./third_party/flutter_k_chart
  flutter_k_chart: ^0.2.0

  # Media
  ## video_player: ^1.0.1
  video_player: ^2.3.0
  ## transparent_image: ^1.0.0
  transparent_image: ^2.0.0
  ## cached_network_image: ^2.5.0
  cached_network_image: ^3.2.0
  ## flutter_gifimage: ^1.0.1
  flutter_gifimage: ^1.0.1
  ## flutter_swiper: ^1.1.6
  flutter_swiper: ^1.1.6
  ## photo_view: ^0.10.3
  photo_view: ^0.13.0
  ## image_picker: ^0.6.7+17
  image_picker: ^0.8.5+3
  ## image_gallery_saver: "^1.6.7"
  image_gallery_saver: ^1.7.1
  ## qr_flutter: ^3.2.0
  qr_flutter: ^4.0.0
  ## qr_code_tools: ^0.0.6
  qr_code_tools: ^0.0.7
  #qr_code_scanner:
  #  git: https://github.com/juliuscanute/qr_code_scanner
  # qr_code_scanner: ^0.7.0
  qr_code_scanner: ^0.3.5
  ## webview_flutter: ^1.0.7
  webview_flutter: ^3.0.4
  ## flutter_inappwebview: ^4.0.0+4
  flutter_inappwebview: ^5.4.3+7
  ## url_launcher: ^5.7.10
  url_launcher: ^6.1.2

  # Wallet
  ## cryptography: ^1.4.1
  cryptography: ^2.0.5
  wallet_sdk_flutter:
    git: https://github.com/metabasenetwork/wallet_sdk_flutter
  flutter_hdkey:
    path: ./third_party/flutter_hdkey
  flutter_dabank:
    path: ./third_party/flutter_dabank
  ## ed25519_dart_base: ^0.0.1
  ed25519_dart_base: ^0.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  ## bloc_test: ^7.1.0
  flutter_lints: ^1.0.0
  # Testing
  ## mockito:
  mockito: ^5.2.0
  # Linting
  ## lint: ^1.3.0
  lint: ^1.8.2
  ## import_sorter: ^4.4.1
  import_sorter: ^4.6.0

  # Code Generators
  ## build_runner: ^1.10.0
  build_runner: ^2.1.11
  ## hive_generator: ^0.8.2
  hive_generator: ^1.1.3
  ## built_value_generator: ^7.1.0
  built_value_generator: ^8.3.0
  ## flutter_native_splash: ^0.1.9
  flutter_native_splash: ^2.1.3+1
  ## flutter_launcher_icons: ^0.8.1
  flutter_launcher_icons: ^0.9.2
  ## date_format: ^1.0.9
  date_format: ^2.0.6
  quiver: ^3.0.1

  # Google Sheets
  ## dotenv: ^2.0.0
  dotenv: ^3.0.0
  ## googleapis: ^0.56.1
  googleapis: ^8.1.0
  ## googleapis_auth: ^0.2.12
  googleapis_auth: ^1.3.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.dev
    - assets/locales/
    - assets/video/splash.mp4
    # Rive animations
    - assets/rive/loading.riv
    - assets/rive/refreshing.riv
    - assets/rive/home.riv
    - assets/rive/wallet.riv
    - assets/rive/invest.riv
    - assets/rive/trade.riv
    - assets/rive/confirming.riv
    - assets/rive/change.riv
    - assets/rive/line.riv
    # Images - Coins
    - assets/images/coin_eth.png
    - assets/images/coin_btc.png
    - assets/images/coin_trx.png
    - assets/images/coin_mars.png
    - assets/images/coin_usdt_trx.png
    - assets/images/coin_usdt_erc.png
    - assets/images/coin_bnb.png
    - assets/images/coin_mnt.png
    - assets/images/coin_usdt_bep.png

    # Images - Logo
    - assets/images/logo.png
    - assets/images/2.0x/logo.png
    - assets/images/3.0x/logo.png
    - assets/images/2.0x/logo_mnt.png
    - assets/images/3.0x/logo_mnt.png
    - assets/images/banner_default.png
    - assets/images/2.0x/banner_default.png
    - assets/images/3.0x/banner_default.png
    - assets/images/empty_wallet.png
    - assets/images/2.0x/empty_wallet.png
    - assets/images/3.0x/empty_wallet.png
    - assets/images/empty_record.png
    - assets/images/2.0x/empty_record.png
    - assets/images/3.0x/empty_record.png
    - assets/images/explorer_bg.png
    - assets/images/help_bg.png
    - assets/images/2.0x/help_bg.png
    - assets/images/3.0x/help_bg.png
    - assets/images/update_bg.png
    - assets/images/2.0x/update_bg.png
    - assets/images/3.0x/update_bg.png
    - assets/images/app_default_logo.png
    - assets/images/2.0x/app_default_logo.png
    - assets/images/2.0x/app_default_logo.png
    # Images -
    - assets/images/wallet_binance.png
    - assets/images/wallet_bitfinex.png
    - assets/images/wallet_bittrex.png
    - assets/images/wallet_coinbase.png
    - assets/images/wallet_huobi.png
    - assets/images/wallet_imtoken.png
    - assets/images/wallet_kraken.png
    - assets/images/wallet_ledger.png
    - assets/images/wallet_okex.png
    - assets/images/wallet_pockmine.png
    - assets/images/wallet_mars.png
    - assets/images/wallet_others.png
    - assets/images/2.0x/wallet_binance.png
    - assets/images/2.0x/wallet_bitfinex.png
    - assets/images/2.0x/wallet_bittrex.png
    - assets/images/2.0x/wallet_coinbase.png
    - assets/images/2.0x/wallet_huobi.png
    - assets/images/2.0x/wallet_imtoken.png
    - assets/images/2.0x/wallet_kraken.png
    - assets/images/2.0x/wallet_ledger.png
    - assets/images/2.0x/wallet_okex.png
    - assets/images/2.0x/wallet_mars.png
    - assets/images/2.0x/wallet_others.png
    - assets/images/3.0x/wallet_pockmine.png
    - assets/images/3.0x/wallet_binance.png
    - assets/images/3.0x/wallet_bitfinex.png
    - assets/images/3.0x/wallet_bittrex.png
    - assets/images/3.0x/wallet_coinbase.png
    - assets/images/3.0x/wallet_huobi.png
    - assets/images/3.0x/wallet_imtoken.png
    - assets/images/3.0x/wallet_kraken.png
    - assets/images/3.0x/wallet_ledger.png
    - assets/images/3.0x/wallet_okex.png
    - assets/images/3.0x/wallet_pockmine.png
    - assets/images/3.0x/wallet_mars.png
    - assets/images/3.0x/wallet_others.png
    # Images - Community
    - assets/images/community_list_1.png
    - assets/images/2.0x/community_list_1.png
    - assets/images/3.0x/community_list_1.png
    - assets/images/community_list_2.png
    - assets/images/2.0x/community_list_2.png
    - assets/images/3.0x/community_list_2.png
    - assets/images/community_list_3.png
    - assets/images/2.0x/community_list_3.png
    - assets/images/3.0x/community_list_3.png
    - assets/images/community_menu_develop.png
    - assets/images/community_menu_market.png
    - assets/images/community_menu_media.png
    - assets/images/community_menu_operations.png
    - assets/images/community_menu_investor.png
    - assets/images/community_menu_education.png
    - assets/images/community_menu_mars.png
    - assets/images/2.0x/community_menu_develop.png
    - assets/images/2.0x/community_menu_market.png
    - assets/images/2.0x/community_menu_media.png
    - assets/images/2.0x/community_menu_operations.png
    - assets/images/2.0x/community_menu_investor.png
    - assets/images/2.0x/community_menu_education.png
    - assets/images/2.0x/community_menu_mars.png
    - assets/images/3.0x/community_menu_develop.png
    - assets/images/3.0x/community_menu_market.png
    - assets/images/3.0x/community_menu_media.png
    - assets/images/3.0x/community_menu_operations.png
    - assets/images/3.0x/community_menu_investor.png
    - assets/images/3.0x/community_menu_education.png
    - assets/images/3.0x/community_menu_mars.png
    # Images - Invest
    - assets/images/airdrop_triangle_bg.png
    - assets/images/airdrop_empty_bg.png
    - assets/images/airdrop_wait_bg.png
    - assets/images/airdrop_join.png
    - assets/images/airdrop_transfer.png
    - assets/images/airdrop_wait.png
    - assets/images/error_record.png
    - assets/images/2.0x/error_record.png
    - assets/images/3.0x/error_record.png
    - assets/images/2.0x/airdrop_triangle_bg.png
    - assets/images/2.0x/airdrop_empty_bg.png
    - assets/images/2.0x/airdrop_wait_bg.png
    - assets/images/2.0x/airdrop_join.png
    - assets/images/2.0x/airdrop_transfer.png
    - assets/images/2.0x/airdrop_wait.png
    - assets/images/3.0x/airdrop_triangle_bg.png
    - assets/images/3.0x/airdrop_empty_bg.png
    - assets/images/3.0x/airdrop_wait_bg.png
    - assets/images/3.0x/airdrop_join.png
    - assets/images/3.0x/airdrop_transfer.png
    - assets/images/3.0x/airdrop_wait.png
    # Images - Trade
    - assets/images/ticker_btn_buy.png
    - assets/images/2.0x/ticker_btn_buy.png
    - assets/images/3.0x/ticker_btn_buy.png
    - assets/images/ticker_btn_sell.png
    - assets/images/2.0x/ticker_btn_sell.png
    - assets/images/3.0x/ticker_btn_sell.png
    - assets/images/ticker_btn_default.png
    - assets/images/2.0x/ticker_btn_default.png
    - assets/images/3.0x/ticker_btn_default.png
    - assets/images/trade_speed.png
    - assets/images/2.0x/trade_speed.png
    - assets/images/3.0x/trade_speed.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: DINPro
      fonts:
        - asset: assets/fonts/DINPro-Medium.ttf
          weight: 500
    - family: IcoMoon
      fonts:
        - asset: assets/icons/icomoon.ttf

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "FFDF0C"
  fill: true
